hackathon/chat/urls.py
# chat/urls.py
from django.urls import path

from .views import *

app_name = 'chat'

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
    path('<str:me_id>/<str:opp_id>/', create_chat_room, name='create_chat_room'),
]

hackathon/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('main.urls', namespace='main')),

    path('users/', include('users.urls', namespace='users')),

    path('recruit/', include('team_build.urls', namespace='recruit')),
    
    path('portfolio/', include('mypf.urls', namespace='portfolio')),

    path('mypage/', include('mypage.urls', namespace='mypage')),

    path('scout/', include('scout.urls', namespace='scout')),
    
    path('chat/', include('chat.urls', namespace='chat')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hackathon/scout/urls.py
from django.urls import path
from .views import *

app_name='scout'

urlpatterns = [
    # 유저 검색
    path('', user, name='user'),
    path('<str:input_role>', user_search, name='user_search'),
    path('search_text/<str:input_text>', user_search_text, name='user_search_text'),

    # 유저 찜
    path('user_like/<int:user_id>', user_like, name="user_like"),
]

hackathon/team_build/urls.py
from django.urls import path
from .views import *

app_name = 'team_build'

urlpatterns = [
    # 모집글 검색
    path('', RecruitListView.as_view(), name='team_build'),
    path('<str:search_word>', recruit_search, name='recruit_role_search'),
    # path('<str:input_location>', recruit_location_search, name='location_search'),
    
    # 모집글
    path('create_recruit/', create_recruit, name='create_recruit'),
    path('update_recruit/<int:id>/', update_recruit, name='update_recruit'),
    path('<int:id>/', detail_recruit, name='detail_recruit'),
    path('delete_recruit/<int:id>/', delete_recruit, name='delete_recruit'),

    # 댓글
    path('detail_recruit/<int:id>/create_comment/', create_comment, name='create_comment'),
    path('detail_recruit/<int:id>/delete_comment/<int:comment_id>/<str:answer_comment>', delete_comment, name='delete_comment'),
    path('detail_recruit/<int:id>/update_comment/<int:comment_id>', update_comment, name='update_comment'),

    # 모집글 찜
    path('recruit_like/<int:recruit_id>', recruit_like, name="recruit_like"),
]

hackathon/users/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

hackathon/scout/models.py
from django.db import models
from django.db.models.deletion import CASCADE

from users.models import User

class LikeUser(models.Model):
    # 어떤 유저의 찜 정보인지
    user = models.CharField(default="", max_length=200)
    # 어떤 유저를 찜했는지 해당 유저 정보를 저장
    # 해당 유저가 지워지면 찜 내역도 사라짐
    user_key = models.ForeignKey(User, on_delete=CASCADE)

hackathon/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField

# from team_build.models import LOCATE_CHOICES

LOCATE_CHOICES = [
    ('','미정'),
    ('서울','서울특별시'),
    ('부산','부산광역시'),
    ('인천','인천광역시'),
    ('대구','대구광역시'),
    ('광주','광주광역시'),
    ('대전','대전광역시'),
    ('울산','울산광역시'),
    ('세종','세종시'),
    ('경기','경기도'),
    ('강원','강원도'),
    ('충남','충청남도'),
    ('충북','충청북도'),
    ('경북','경상북도'),
    ('경남','경상남도'),
    ('전북','전라북도'),
    ('전남','전라남도'),
    ('제주','제주도'),
]
# User
CAREER_CHOICES = [
    ('0','1년 미만'),
    ('1','1년'),
    ('2','2년'),
    ('3','3년'),
    ('4','4년'),
    ('5','5년'),
    ('6','6년'),
    ('7','7년'),
    ('8','8년'),
    ('9','9년'),
    ('10','10년 이상'),
]

STATE_CHOICES = [
    ('','미입력'),
    ('ATTENDING','재학중'),
    ('ABSENCE','휴학중'),
    ('SEARCHING','구직중'),
    ('WORKING','재직중'),
]

ROLE_CHOICES = [
    ('Developer', '개발자'),
    ('Designer', '디자이너'),
    ('Planner', '기획자'),
    ('Etc', '그 외'),
]

# 회원 정보
class User(AbstractUser):
    image = models.ImageField(default="image/users/none/profile_default.png", upload_to="image/users" , blank=True, null=False)
    name = models.CharField(default='', max_length=300)
    birth_date = models.DateField(default=timezone.now)
    address_sido = models.CharField(default='', choices=LOCATE_CHOICES, max_length=200)
    address_gungu = models.CharField(default='', max_length=200)
    career = models.CharField(default='0', max_length=200, choices=CAREER_CHOICES)
    state = models.CharField(default='', blank=True, null=False, max_length=200, choices=STATE_CHOICES)
    role = MultiSelectField(default='Etc', choices=ROLE_CHOICES, max_choices=4, max_length=200)
    intro = models.TextField(default="", blank=True, null=False)

hackathon/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import *

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
        'image', 'name', 'birth_date', 'address_sido',
        'address_gungu','career', 'state', 'role',
        'intro']

class CustomRegisterForm(UserCreationForm):
    password1 = forms.CharField(max_length=16, widget = forms.PasswordInput(attrs={'class':'password1-input1', 'placeholder':'8글자 이상. 숫자로만 입력할 수 없음'}))
    password2 = forms.CharField(max_length=16, widget = forms.PasswordInput(attrs={'class':'password2-input1', 'placeholder':'비밀번호 재입력'}))
    class Meta:
        model = User
        fields = ['name', 'image', 'username', 'password1', 'password2',
        'birth_date', 'address_sido','address_gungu',
        'career', 'state', 'role', 'intro']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'id-input1', 'placeholder': '150 글자 이하의 문자, 숫자 및 @ / . / + / - / _ 조합'}),
            # 'password1': forms.PasswordInput(attrs={'class':'password1-input1', 'placeholder':'8글자 이상. 숫자로만 입력할 수 없음'}), 
            # 'password2': forms.PasswordInput(attrs={'class':'password2-input1', 'placeholder':'비밀번호 재입력'}),
            'image': forms.ClearableFileInput(attrs={'class': 'image-input1', 'placeholder': ''}), 
            'name': forms.TextInput(attrs={'class': 'name-input1', 'placeholder': ''}), 
            'birth_date': forms.DateInput(attrs={'class': 'birthday-input1', 'placeholder': ''}), 
            'address_sido': forms.Select(attrs={'class': 'sido-input2', 'placeholder': ''}),
            'address_gungu': forms.TextInput(attrs={'class': 'gungu-input2', 'placeholder': '00군 혹은 00구'}),
            'career': forms.Select(attrs={'class': 'career-input2', 'placeholder': ''}),
            'state': forms.Select(attrs={'class': 'state-input2', 'placeholder': ''}), 
            'role': forms.CheckboxSelectMultiple(attrs={'class': 'role-input2', 'placeholder': ''}),
            'intro': forms.Textarea(attrs={'class': 'intro-input3', 'placeholder': '간단하게 자신을 나타내는 소개글을 적어주세요'})
        }

        labels = {
            'username': 'ID',
            'password1': '비밀번호', 
            'password2': '비밀번호 재입력',
            'image': '프로필 사진', 
            'name': '이름', 
            'birth_date': '생년월일', 
            'address_sido': '주소(시/도)',
            'address_gungu': '주소(군/구)',
            'career': '경력',
            'state': '상태', 
            'role': '희망포지션',
            'intro': '한줄소개'
        }

        # def __init__(self, *args, **kwargs):
        #     super(CustomRegisterForm, self).__init__(*args, **kwargs)
        #     self.fields['password1'].widget = forms.PasswordInput(attrs={'class':'password1-input1', 'placeholder':'8글자 이상. 숫자로만 입력할 수 없음'})
        #     self.fields['password2'].widget = forms.PasswordInput(attrs={'class':'password2-input1', 'placeholder':'비밀번호 재입력'})


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'id-input', 'placeholder': '아이디'}),
            'password': forms.PasswordInput(attrs={'class':'password-input', 'placeholder':'비밀번호'}),
        }
        labels = {
            'username':'아이디',
            'password':'비밀번호',
        }

hackathon/scout/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from django.core.paginator import Paginator
from django.db.models import Q

from users.models import User
from .models import LikeUser

PAGE_RANGE = 5

LIST_RANGE = 12

# 유저 검색 기능 ( 아직 역할 검색만 )
def user(request):
    if request.user.id:
        user_instance = User.objects.get(pk=request.user.id)
    else:
        user_instance = None

    users = User.objects.all().order_by('-id')
    max_index = len(users) / LIST_RANGE

    paginator = Paginator(users, LIST_RANGE)
    page = request.GET.get('page')
    users = paginator.get_page(page)
    # max_index = len(paginator.page_range)

    current_page = int(page) if page else 1
    start_index = int((current_page - 1) / PAGE_RANGE) * PAGE_RANGE
    end_index = start_index + PAGE_RANGE
    if end_index >= max_index:
        end_index = max_index

    page_range = []
    for index in range(int(start_index), int(end_index) + 1):
        page_range.append(index + 1)

    context = {
        'current_user':user_instance,
        'users': users,
        'page_range':page_range,
    }
    return render(request, 'scout/user.html', context)

def user_search(request, input_role):
    current_user = None
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    
    results = User.objects.filter(Q(role__icontains=input_role)).order_by('-id')
    max_index = len(results) / LIST_RANGE

    paginator = Paginator(results, LIST_RANGE)
    page = request.GET.get('page')
    users = paginator.get_page(page)

    current_page = int(page) if page else 1
    start_index = int((current_page - 1) / PAGE_RANGE) * PAGE_RANGE
    end_index = start_index + PAGE_RANGE
    if end_index >= max_index:
        end_index = max_index
    
    page_range = []
    for index in range(int(start_index), int(end_index) + 1):
        page_range.append(index + 1)
    
    context = {
        'current_user':current_user,
        'users':users,
        'page_range':page_range,
    }
    return render(request, 'scout/user_search.html', context)

def user_search_text(request, input_text):
    if len(input_text) <= 1:
        messages.error(request, '두 글자 이상 입력해주세요.')

    results = User.objects.filter(
        Q(name__icontains=input_text) | 
        Q(address_sido__icontains=input_text) | 
        Q(address_gungu__icontains=input_text) | 
        Q(career__icontains=input_text) |
        Q(state__icontains=input_text)
        ).order_by('-id')
    max_index = len(results) / LIST_RANGE

    paginator = Paginator(results, LIST_RANGE)
    # print(User.objects.filter(Q(name__icontains=input_text) & Q(address_sido__icontains=input_text) & Q(address_gungu__icontains=input_text)))
    page = request.GET.get('page')
    users = paginator.get_page(page)

    current_page = int(page) if page else 1
    start_index = int((current_page - 1) / PAGE_RANGE) * PAGE_RANGE
    end_index = start_index + PAGE_RANGE
    if end_index >= max_index:
        end_index = max_index
    
    page_range = []
    for index in range(int(start_index), int(end_index) + 1):
        page_range.append(index + 1)

    context = {
        'users':users,
        'page_range':page_range,
    }
    return render(request, 'scout/user_search.html', context)

###### 찜 기능 ######
# 찜하기 버튼 누를 때
def user_like(request, user_id):
    like_object = LikeUser.objects.filter(user=request.user.id, user_key=user_id)
    if like_object:
        like_object.delete()
    else:
        like_object = LikeUser()
        like_object.user = request.user.id
        like_object.user_key = User.objects.get(pk=user_id)
        like_object.save()
    return redirect('scout:user')

hackathon/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse

from .models import *
from .forms import *

###### 로그인 페이지 ######
# 로그인 페이지, 로그인 기능 #
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid(): # 유효성 검사
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request=request, username=username, password=password)
            if user is not None:
                login(request, user)
            else:
                return HttpResponse('입력 정보가 올바르지 않습니다.')
        return redirect("main:main")
    else:
        form = LoginForm()
        return render(request, 'users/login.html', {'form':form})

# 로그아웃 #
def logout_view(request):
    logout(request)
    return redirect("main:main")

# 회원가입 페이지, 회원가입 기능 #
def signup_view(request):
    if request.method == "POST":
        form = CustomRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
        return redirect("main:main")
    else:
        form = CustomRegisterForm()
        return render(request, 'users/signup.html', {'form': form})

hackathon/templates/scout/user.html
{% extends '../base.html' %}
    <head>
        {% block extrahead %}
        {% load static %}
            <link rel="stylesheet" href="{% static 'css/base.css' %}">
            <link rel="stylesheet" href="{% static 'css/team_build/team_build.css' %}">
            <link rel="stylesheet" href="{% static 'css/scout/user.css' %}">
            <style>
                .profile-img {
                    background-image: url('../../media/{{current_user.image}}');
                }
            </style>
        {% endblock %}
    </head>
    {% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="message-container">                                
                <h1>{{ message.tags}}</h1>
                <br>
                {{ message.message }}
                <br><br>
                <a href="{% url 'scout:user' %}">확인</a>
            </div>
        {% endfor %}
    {% endif %}

    <div>
        <div class="search-box">
            <div class="search-container">
                <p>어떤 팀원을 찾으시나요?</p>
                <div class="search-wrapper">
                    <a href="{% url 'scout:user' %}">전체</a>
                    <a href="{% url 'scout:user_search' 'Developer' %}">개발자</a>
                    <a href="{% url 'scout:user_search' 'Planner' %}">기획자</a>
                    <a href="{% url 'scout:user_search' 'Designer' %}">디자이너</a>
                    <a href="{% url 'scout:user_search' 'Editor' %}" style="margin-right: 0;">편집자</a>
                    <div class="stick">|</div>
                    <select name="" id="" onchange="location.href='/scout/search_text/'+this.value">
                        <option value="">시/도</option>
                        <option value="서울">서울특별시</option>
                        <option value="부산">부산광역시</option>
                        <option value="인천">인천광역시</option>
                        <option value="대구">대구광역시</option>
                        <option value="광주">광주광역시</option>
                        <option value="대전">대전광역시</option>
                        <option value="울산">울산광역시</option>
                        <option value="세종">세종시</option>
                        <option value="경기">경기도</option>
                        <option value="강원">강원도</option>
                        <option value="충남">충청남도</option>
                        <option value="충북">충청북도</option>
                        <option value="경북">경상북도</option>
                        <option value="경남">경상남도</option>
                        <option value="전북">전라북도</option>
                        <option value="전남">전라남도</option>
                        <option value="제주">제주도</option>
                    </select>

                    <div class="stick">|</div>

                    <select name="" id="" onchange="location.href='/scout/search_text/'+this.value">
                        <option value="">상태</option>
                        <option value="ATTENDING">재학중</option>
                        <option value="ABSENCE">휴학중</option>
                        <option value="SEARCHING">구직중</option>
                        <option value="WORKING">재직중</option>
                    </select>
                    
                    <div class="form">
                        <input type="text" name="input-text" placeholder="검색어를 입력하세요.">
                        <button onclick="search()"></button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            function search() {
                location.href = "/scout/search_text/" + document.getElementsByName("input-text")[0].value
            }
        </script>

        {% if messages %}
            {% for message in messages %}
                <div class="message-container">                                
                    <h1>{{message.tags}}</h1>
                    <br>
                    {{ message.message }}
                    <br><br>
                    <a href="{% url 'recruit:team_build' %}">확인</a>
                </div>
            {% endfor %}
        {% endif %}

        <div class="users-container">
        {% block users %}
            {% for user_instance in users %}
                <div class="user-card" onclick="location.href='/portfolio/{{user_instance.id}}'">
                    <div class="card-nav">
                        <a href="{% if user.is_authenticated %} {% url 'chat:create_chat_room' user.id user_instance.id %} {% else %} {% url 'users:login' %} {% endif %}">
                            <div class="chat" style="background-image: url('../../static/img/scout/chat.png');"></div>
                        </a>
                        <a href="{% if user.is_authenticated %} {% url 'scout:user_like' user_instance.id %} {% else %} {% url 'users:login' %} {% endif %}">
                            <div class="wish" style="background-image: url('../../static/img/scout/like.png');"></div>
                        </a>
                    </div>
                    
                    <hr>

                    <img class="user-img" src="../../media/{{user_instance.image}}" alt="프로필 사진">

                    <div class="user-name">
                        {{user_instance.name}}
                    </div>
            
                    <div class="user-address">
                        {{user_instance.get_address_sido_display}}
                    </div>
                    
                    <div class="card-content"> 
                        <p class="user-info">
                            <br>
                            #{{user_instance.get_role_display}} #{{user_instance.get_state_display}}
                            <br><br>
                        </p>
                    
                        <div class="user-intro">
                            {{user_instance.intro}}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endblock %}
        </div>
        <div class="page-container"> 
            <div class="page-wrapper">
                {% for page in page_range %}
                    <a class="page-box" href="?page={{page}}">{{page}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

hackathon/templates/scout/user_search.html
{% extends 'scout/user.html' %}
<head>
    {% block extrahead %}
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/team_build/team_build.css' %}">
        <link rel="stylesheet" href="{% static 'css/scout/user.css' %}">
        <style>
            .logo-img {
                background-image: url('{% static "img/logo.png" %}');
            }

            .profile-img {
                background-image: url('{% if user.is_anonymous %} ../../media/image/users/none/profile_default.png {% else %} ../../media/{{current_user.image}} {% endif %}');
            }

            .footer-img {
                background-image: url('{% static "img/footer_logo.png" %}');
            }
        </style>
    {% endblock %}
</head>
    {% block users %}
        {% for user_instance in users %}
        <div class="user-card" onclick="location.href='/portfolio/{{user_instance.id}}'">
            <div class="card-nav">
                <a href="{% url 'chat:create_chat_room' user.id user_instance.id %}">
                    <div class="chat" style="background-image: url('../../static/img/scout/chat.png');"></div>
                </a>
                <a href="{% if user.is_authenticated %} {% url 'scout:user_like' user_instance.id %} {% else %} {% url 'users:login' %} {% endif %}">
                    <div class="wish" style="background-image: url('../../static/img/scout/like.png');"></div>
                </a>
            </div>
            
            <hr>

            <img class="user-img" src="../../media/{{user_instance.image}}" alt="프로필 사진">
            
            <div class="user-name">
                {{user_instance.name}}
            </div>
    
            <div class="user-address">
                {{user_instance.get_address_sido_display}}
            </div>
            
            <div class="card-content"> 
                <p class="user-info">
                    <br>
                    #{{user_instance.get_role_display}} #{{user_instance.get_state_display}}
                    <br><br>
                </p>
            
                <div class="user-intro">
                    {{user_instance.intro}}
                </div>
            </div>
        </div>
        {% endfor %}
    {% endblock %}