hackathon/chat/urls.py
# chat/urls.py
from django.urls import path

from .views import *

app_name = 'chat'

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
    path('<str:me_id>/<str:opp_id>/', create_chat_room, name='create_chat_room'),
]

hackathon/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('main.urls', namespace='main')),

    path('users/', include('users.urls', namespace='users')),

    path('recruit/', include('team_build.urls', namespace='recruit')),
    
    path('portfolio/', include('mypf.urls', namespace='portfolio')),

    path('mypage/', include('mypage.urls', namespace='mypage')),

    path('scout/', include('scout.urls', namespace='scout')),
    
    path('chat/', include('chat.urls', namespace='chat')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hackathon/team_build/urls.py
from django.urls import path
from .views import *

app_name = 'team_build'

urlpatterns = [
    # 모집글 검색
    path('', RecruitListView.as_view(), name='team_build'),
    path('<str:search_word>', recruit_search, name='recruit_role_search'),
    # path('<str:input_location>', recruit_location_search, name='location_search'),
    
    # 모집글
    path('create_recruit/', create_recruit, name='create_recruit'),
    path('update_recruit/<int:id>/', update_recruit, name='update_recruit'),
    path('<int:id>/', detail_recruit, name='detail_recruit'),
    path('delete_recruit/<int:id>/', delete_recruit, name='delete_recruit'),

    # 댓글
    path('detail_recruit/<int:id>/create_comment/', create_comment, name='create_comment'),
    path('detail_recruit/<int:id>/delete_comment/<int:comment_id>/<str:answer_comment>', delete_comment, name='delete_comment'),
    path('detail_recruit/<int:id>/update_comment/<int:comment_id>', update_comment, name='update_comment'),

    # 모집글 찜
    path('recruit_like/<int:recruit_id>', recruit_like, name="recruit_like"),
]

hackathon/users/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

hackathon/team_build/models.py
from django.db import models
from django.utils import timezone
from multiselectfield import MultiSelectField

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname('users'))))
from users.models import *

from django.db.models.deletion import CASCADE



# Recruit
TEAM_MEMBERS_CHOICES = [
    ('1','1명'),
    ('2','2명'),
    ('3','3명'),
    ('4','4명'),
    ('5','5명 이상'),
]

LEVEL_CHOICES = [
    ('0', '아이디어 구상 단계'),
    ('1', '초기 개발 단계'),
    ('2', '프로토타입 완성 단계'),
    ('3', '배포 및 상용화 단계'),
    ('4', '서비스 확장 단계'),
]

LOCATE_CHOICES = [
    ('','미정'),
    ('서울','서울특별시'),
    ('부산','부산광역시'),
    ('인천','인천광역시'),
    ('대구','대구광역시'),
    ('광주','광주광역시'),
    ('대전','대전광역시'),
    ('울산','울산광역시'),
    ('세종','세종시'),
    ('경기','경기도'),
    ('강원','강원도'),
    ('충남','충청남도'),
    ('충북','충청북도'),
    ('경북','경상북도'),
    ('경남','경상남도'),
    ('전북','전라북도'),
    ('전남','전라남도'),
    ('제주','제주도'),
]

ROLE_CHOICES = [
    ('Developer', '개발자'),
    ('Designer', '디자이너'),
    ('Planner', '기획자'),
    ('Editor', '편집자'),
]
# 팀원 모집 글
class Recruit(models.Model):
    # user = models.ForeignKey(User, on_delete=CASCADE, null=True)
    writer = models.CharField(default='', max_length=200)
    writer_username = models.CharField(default='', max_length=200)
    title = models.CharField(default='', max_length=300) # 프로젝트 한줄 설명으로 들어갈 것
    team_name = models.CharField(default='', max_length=200)
    service = models.CharField(default='', max_length=200)
    team_members = models.CharField(
        default='1',
        blank=True,
        null=False,
        max_length=200,
        choices=TEAM_MEMBERS_CHOICES
        )
    service_level = models.CharField(
        default='0',
        null=False,
        blank=True,
        max_length=200,
        choices=LEVEL_CHOICES
        )
    founding_date = models.DateField(default=timezone.now, null=False, blank=True)
    locate = models.CharField(default='', null=False, blank=True, max_length=2, choices=LOCATE_CHOICES)
    image = models.ImageField(
        default='image/team_build/none/img_default.png',
        upload_to="image/team_build/",
        blank=True,
        null=False
        )
    # 추후 기본 이미지로 넣을 경로 찾아서 default 에 지정 필요
    role = MultiSelectField(default='', choices=ROLE_CHOICES, max_choices=4, max_length=100)
    # role = models.CharField(max_length=2, choices=ROLE_CHOICES)
    detail = models.TextField(blank=True, null=True)

class Comment(models.Model):
    recruit_id = models.ForeignKey(Recruit, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=200)

class CommentAnswer(models.Model):
    comment_id = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=200)

class LikeRecruit(models.Model):
    # 어떤 유저의 찜 정보인지 user id를 저장(request.user 값이 들어갈 것임)
    user = models.CharField(default="", max_length=200)
    # 해당 유저가 어떤 모집글을 찜했는지 해당 모집글의 id를 저장
    recruit_key = models.ForeignKey(Recruit, on_delete=CASCADE)

hackathon/team_build/forms.py
from django import forms
from .models import *

class RecruitForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ['title', 'team_name', 'service', 
         'service_level', 'locate', 'team_members',
        'image', 'role', 'detail']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'recruit-title', 'placeholder': '제목'}),
            'team_name': forms.TextInput(attrs={'class': 'recruit-text-input', 'placeholder':'팀이름'}),
            'service': forms.TextInput(attrs={'class': 'recruit-text-input', 'placeholder':'서비스'}),
            'service_level': forms.Select(attrs={'class': 'recruit-select'}),
            'locate': forms.Select(attrs={'class': 'recruit-select'}),
            'team_members': forms.Select(attrs={'class': 'recruit-select'}),
            'role': forms.CheckboxSelectMultiple(attrs={'class': 'recruit-role'}),
            'image': forms.FileInput(attrs={'class': 'recruit-image'}),
            'detail': forms.Textarea(attrs={'class': 'recruit-detail'}),
        }

        labels = {
            'title': '제목:',
            'team_name': '팀명:',
            'service': '서비스:',
            'service_level': '서비스 단계:',
            'locate': '활동장소:',
            'team_members': '인원:',
            'role': '모집 포지션:',
            'image': '이미지:',
            'detail': '추가설명:',
        }

hackathon/team_build/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404

from .models import *
from users.models import User
from .models import LikeRecruit
from .forms import *

from django.views.generic import ListView

from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages

import json

PAGE_RANGE = 5

LIST_RANGE = 5

###### 팀 빌딩 페이지 ######
# 1. 팀빌딩 메인 
#    팀빌딩 키워드 검색 기능 -> query 방식 #
class RecruitListView(ListView):
    model = Recruit
    paginate_by = LIST_RANGE
    # 리스트를 team_build.html 템플릿으로 보낼 것임
    template_name = 'team_build/team_build.html'
    # 템플릿에서 리스트를 호출할 때 'recruit_list'로 호출
    context_object_name = 'recruit_list'

    def get_queryset(self):
        # 사용자가 입력한 검색어를 저장 -> GET 방식, 검색 input태그 name == 'q'
        # q 라는 파라미터에 할당된 값을 불러옴
        search_word = self.request.GET.get('q','')
        
        # 검색어가 포함된 게시글 리스트를 저장할 변수
        recruit_list = Recruit.objects.all()

        if search_word: # 만약 검색어가 존재하는 경우
            if len(search_word) > 1: # 두 글자 이상
                recruit_list = recruit_list.filter(
                    Q(title__icontains=search_word) | 
                    Q(writer__icontains=search_word) |
                    Q(team_name__icontains=search_word) |
                    Q(service__icontains=search_word) |
                    Q(detail__icontains=search_word)
                    )
                recruit_list = recruit_list.order_by('-id')
                return recruit_list
            else:
                messages.error(self.request, '두 글자 이상 입력해주세요.')
        # 검색어가 없는 기본 상태일 때는, 모든 Recruit 객체 리스트를
        # recruit_list에 담아서 반환
        # id 내림차순 -> 최신순으로 나열
        recruit_list = recruit_list.order_by('-id')
        return recruit_list

    # context에 리스트뿐만 아니라, 추가적으로 정보를 더 담는 함수
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        # 페이지 이동 버튼에서 최대 5개의 페이지만 띄울 것임
        page_num_range = PAGE_RANGE
        max_index = len(paginator.page_range)

        # 현재 페이지 정보를 불러옴
        page = self.request.GET.get('page')
        # 현재 페이지 정보가 0이면 curreunt_page를 1로 저장
        current_page = int(page) if page else 1
        # 
        start_index = int((current_page - 1) / page_num_range) * page_num_range
        end_index = start_index + page_num_range
        if end_index >= max_index:
            end_index = max_index
        
        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        if self.request.user.id:
            context['current_user'] = User.objects.get(pk=self.request.user.id)
        else:
            context['current_user'] = None

        return context

# 2. 팀빌딩 직무 검색 기능 #
def recruit_search(request, search_word):
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    else:
        current_user = None

    results = Recruit.objects.filter(Q(role__icontains=search_word) | Q(locate__icontains=search_word)).distinct()
    max_index = len(results) / LIST_RANGE

    results = results.order_by('-id')
    # distinct() : 중복된 객체 제외
    paginator = Paginator(results, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    current_page = int(page) if page else 1
    start_index = int((current_page - 1) / PAGE_RANGE) * PAGE_RANGE
    end_index = start_index + PAGE_RANGE
    if end_index >= max_index:
        end_index = max_index

    page_range = []
    for index in range(int(start_index), int(end_index) + 1):
        page_range.append(index + 1)

    context = {
        'current_user':current_user,
        'posts':posts,
        'page_range':page_range,
    }
    return render(request, 'team_build/recruit_search.html' ,context)

# 2-1. 팀 빌딩 지역 검색 기능 #
# def recruit_location_search(request, input_location):
#     if request.user.id:
#         current_user = User.objects.get(pk=request.user.id)
#     else:
#         current_user = None

#     results = Recruit.objects.filter(locate=input_location).distinct()
#     paginator = Paginator(results, 5)
#     page = request.GET.get('page')
#     posts = paginator.get_page(page)
#     context = {
#         'current_user':current_user,
#         'posts':posts,
#     }
#     return render(request, 'team_build/recruit_location_search.html', context)

# 3. 팀빌딩 글 작성 페이지, 기능 #
def create_recruit(request):
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    else:
        current_user = None

    recruits_form = RecruitForm()
    if request.method == "POST":
        recruits_form = RecruitForm(request.POST, request.FILES)
        if recruits_form.is_valid():
            new_form = recruits_form.save(commit=False)
            new_form.writer = request.user.name
            new_form.writer_username = request.user
            new_form.save()
        return redirect('team_build:team_build')
    else:
        context = {
            'current_user':current_user,
            'form': recruits_form,
        }
        return render(request, 'team_build/create_recruit.html', context)

# 4-1. 팀빌딩 게시글 자세히 보기 #
def detail_recruit(request, id):
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    else:
        current_user = None

    recruit_instance = get_object_or_404(Recruit, pk=id)
    comments_instance = Comment.objects.filter(recruit_id=id).order_by('-id')
    ans_comment_instance = CommentAnswer.objects.all()

    paginator = Paginator(comments_instance, 6)
    page = request.GET.get('page')
    comments = paginator.get_page(page)


    context ={
        'current_user':current_user,
        'obj': recruit_instance,
        'id': id,
        'comments': comments,
        'ans_comments':ans_comment_instance,
    }
    return render(request, 'team_build/detail_recruit.html', context)

# 4-2. 팀빌딩 게시글 삭제하기 #
def delete_recruit(request, id):
    # 해당 게시글 불러오기
    recruit_instance = get_object_or_404(Recruit, pk=id)

    # 게시글 작성자랑 로그인 유저랑 같으면
    if str(request.user) == recruit_instance.writer_username:
        recruit_instance.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('team_build:team_build')
    else:
        messages.error(request, "타인이 작성한 게시글은 삭제할 수 없습니다.")
        return redirect('team_build:detail_recruit', id)

# 4-3. 팀빌딩 게시글 수정하기 #
def update_recruit(request, id):
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    else:
        current_user = None

    recruit_instance = get_object_or_404(Recruit, pk=id)
    
    # POST 요청
    if request.method == "POST":
        # 폼 생성 및 요청에 의한 데이터로 채우기
        recruit_update_form = RecruitForm(request.POST, request.FILES, instance=recruit_instance)

        # 폼이 유효한가?
        if recruit_update_form.is_valid():
            # 데이터를 요청받은 내용으로 처리
            recruit_update_form.save()
        return redirect('team_build:team_build')

    else:
        form = RecruitForm(instance=recruit_instance)
        context = {
            'current_user':current_user,
            'form': form,
            'id': id,
        }
        return render(request, 'team_build/update_recruit.html', context)




###### 모집글 댓글 ######
# 1. 댓글 작성
def create_comment(request, id):
    username = request.user
    
    if json.loads(request.body).get('answer_comment') == 'True':
        new_comment = CommentAnswer()
        new_comment.comment_id = Comment.objects.get(pk=json.loads(request.body).get('comment_id'))
        
    else:
        new_comment = Comment()
        new_comment.recruit_id = Recruit.objects.get(pk=id)

    new_comment.content = json.loads(request.body).get('text')
    new_comment.user = get_object_or_404(User, username=username)
    new_comment.pub_date = timezone.now()
    new_comment.save()
    
    return HttpResponse(status=200)

# 2. 댓글 수정
def update_comment(request, id, comment_id):
    if json.loads(request.body).get('answer_comment') == "False":
        comment_instance = get_object_or_404(Comment, id=comment_id)
    else:
        comment_instance = get_object_or_404(CommentAnswer, id=comment_id)
    
    comment_instance.content = json.loads(request.body).get('text')
    comment_instance.save()
    
    return HttpResponse(status=200)

# 3. 댓글 삭제
def delete_comment(request, id, comment_id, answer_comment):
    # 해당 댓글 불러오기
    if answer_comment == 'False':
        comment_instance = get_object_or_404(Comment, pk=comment_id)
    else:
        comment_instance = get_object_or_404(CommentAnswer, pk=comment_id)
        
    # 댓글 작성자랑 로그인 유저랑 같으면
    if str(request.user) == comment_instance.user.username:
        comment_instance.delete()


    return HttpResponse(status=200)    

###### 찜 기능 ######
# 찜하기 버튼 누를 때 실행
def recruit_like(request, recruit_id):
    like_object = LikeRecruit.objects.filter(user=request.user.id, recruit_key=recruit_id)
    # 만약 이미 찜이 되어있는 상태라면,(=찜 해제 버튼을 누른 경우)
    if like_object:
        # 찜 해제(테이블 삭제)
        like_object.delete()
    # 해당 테이블이 없는 경우(=찜 목록에 없는 경우, =찜하기 버튼을 누른 경우)
    else:
        # 찜 설정(테이블 생성)
        like_object = LikeRecruit()
        like_object.user = request.user.id
        like_object.recruit_key = Recruit.objects.get(pk=recruit_id)
        like_object.save()
    return redirect('team_build:team_build')

hackathon/templates/team_build/detail_recruit.html
{% extends '../base.html' %}
    <head>
        {% load static %}
        {% block extrahead %}
        <link rel="stylesheet" href="../../../static/css/base.css">
        <link rel="stylesheet" href="../../../static/css/team_build/detail_recruit.css">
        <style>
            .logo-img {
                background-image: url('../../static/img/logo.png');
            }

            .profile-img {
                background-image: url('{% if current_user %}../../../media/{{current_user.image}} {% else %} ../../media/users/none/profile_default.png {% endif %}');
            }
        </style>
        {% endblock %}
    </head>
{% block content %}
    <div id="recruit-id" style="display: none;">{{obj.id}}</div>
    <div class="back-box">
        <div class="title-box">
            <div class="title .item-margin">{{obj.title}}</div>
            <div style="font-size: 12px; display: flex; align-items: flex-end;">{{obj.writer}}</div>
        </div>
        <div class="overview-box item-margin">
            <div class="overview-item">
                <div class="small-title">팀 소개</div>
                <p>팀이름: {{obj.team_name}}</p>
                <p>서비스: {{obj.service}}</p>
                <p>서비스 레벨: {{obj.get_service_level_display}}</p>
            </div>
            <div class="overview-item">
                <div class="small-title">모집상세</div>
                <p>지역: {{obj.get_locate_display}}</p>
                <p>팀원: {{obj.get_team_members_display}}</p>
                <p>역할: {{obj.get_role_display}}</p>
            </div>
        </div>
        <div 
        class="image-box item-margin"
        style="background-image: url('../../../media/{{obj.image}}');">
        </div>
        <div class="detail-box item-margin">
            <p>{{obj.detail}}</p>
        </div>

        {% if obj.writer_username == user.username %}
        <div style="display: flex; flex-direction: row; justify-content: flex-end;">
            <button class="comment-btn-small" onclick="location.href='/recruit/update_recruit/{{obj.id}}/'">수정</button>
            <button class="comment-btn-small" onclick="location.href='/recruit/delete_recruit/{{obj.id}}/'">삭제</button>
        </div>
        {% endif %}
    </div>

    <div class="back-box">
        <div class="comment-create-box" style="padding-left: 10%; padding-right: 10%;">
            <div class="small-profile-img"></div>
            <input type="text" class="comment-input" onkeydown="submitEnter(this)" placeholder="댓글 입력"/>
            <button class="comment-btn" onclick="submitBtn(this)">작성</button>
        </div>

        <div class="empty"></div>
        <div class="empty"></div>

        {% for comment in comments %}
        <div class="comment-box" comment_id="{{comment.id}}">
            <div class="comment-item row" style="flex-grow: 1;">
                <div class="small-profile-img">
                    <img src="../../../media/{{comment.user.image}}">
                </div>
                <div class="comment-item col">
                    <div class="comment-item row">
                        <div class="small-title">{{comment.user.name}}</div>
                        <p style="font-size: 5px; display: inline;">({{comment.date}})</p>
                    </div>
                    <div class="comment-item">{{comment.content}}</div>
                    <div class="comment-item row" style="display: flex; justify-content: flex-end;">
                        <button class="comment-btn-small" onclick="deleteBtn1(this)" {% if comment.user.username != user.username %} style="display: none;"{% endif %}>삭제</button>
                        <button class="comment-btn-small" onclick="updateBtn(this)" {% if comment.user.username != user.username %} style="display: none;"{% endif %}>수정</button>
                        <button class="comment-btn-small" onclick="answerBtn(this)">답글</button>
                    </div>
                    <div class="comment-create-box">
                    </div>
                </div>
            </div>
            <div class="line"></div>
                {% for ans_comment in ans_comments %}
                {% if comment.id == ans_comment.comment_id.id %}
                <div class="answer-comment-box comment-item" comment_id="{{ans_comment.id}}">
                    <div class="comment-item row">
                        <div class="small-profile-img">
                            <img src="../../../media/{{ans_comment.user.image}}">
                        </div>
                        <div class="comment-item col">
                            <div class="comment-item row">
                                <div class="small-title">{{ans_comment.user.name}}</div>
                                <p style="font-size: 5px; display: inline;">({{ans_comment.date}})</p>
                            </div>
                            <div class="comment-item">{{ans_comment.content}}</div>
                            <div class="comment-item row" style="display: flex; justify-content: flex-end;">
                                <button class="comment-btn-small" onclick="deleteBtn2(this)" {% if ans_comment.user.username != user.username %} style="display: none;"{% endif %}>삭제</button>
                                <button class="comment-btn-small" onclick="updateBtn2(this)" {% if ans_comment.user.username != user.username %} style="display: none;"{% endif %}>수정</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line"></div>
                {% endif %}
                {% endfor %}
        </div>
        {% endfor %}

        <div style="text-align: center;">
            {% if comments.has_previous %}
            <a href="?page={{comments.previous_page_number}}"> < </a>
            {% endif %}
            <span> {{comments.number}} </span>
            <span> / </span>
            <span> {{comments.paginator.num_pages}} </span>
            {% if comments.has_next %}
                <a href="?page={{comments.next_page_number}}"> > </a>
            {% endif %}
        </div>
    </div>


        <script type="text/javascript" src="../../../static/js/team_build/detail_recruit.js"></script>

{% endblock %}

hackathon/templates/team_build/team_build.html
{% extends '../base.html' %}
    <head>
        {% load static %}
        {% block extrahead %}
        <link rel="stylesheet" href="../../static/css/base.css">
        <link rel="stylesheet" href="../../static/css/team_build/team_build.css">
        <style>
            .logo-img {
                background-image: url('../../static/img/logo.png');
            }

            .profile-img {
                background-image: url('{% if current_user %}../../media/{{current_user.image}} {% else %} ../../media/users/none/profile_default.png {% endif %}');
            }
        </style>
        {% endblock %}
    </head>
    {% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="message-container">                                
                <h1>{{ message.tags}}</h1>
                <br>
                {{ message.message }}
                <br><br>
                <a href="{% url 'recruit:team_build' %}">확인</a>
            </div>
        {% endfor %}
    {% endif %}

    <div>
        <a class="create-img" href="{% if user.is_authenticated %} {% url 'team_build:create_recruit' %} {% else %} {% url 'users:login' %} {% endif %}">
            <div style="background-image: url('../../static/img/team_build/create_recruit_icon.png');"></div>
        </a>
        <div class="search-box">
            <div class="search-container">
                <p>어떤 프로젝트를 찾으시나요?</p>
                <div class="search-wrapper">
                    <a href="{% url 'team_build:team_build' %}">전체</a>
                    <a href="{% url 'team_build:recruit_role_search' 'Developer' %}">개발자</a>
                    <a href="{% url 'team_build:recruit_role_search' 'Planner' %}">기획자</a>
                    <a href="{% url 'team_build:recruit_role_search' 'Designer' %}">디자이너</a>
                    <a href="{% url 'team_build:recruit_role_search' 'Editor' %}" style="margin-right: 0;">편집자</a>
                    <div class="stick">|</div>
                    <select name="" id="" onchange="location.href='/recruit/'+this.value">
                        <option value="">시/도</option>
                        <option value="서울">서울특별시</option>
                        <option value="부산">부산광역시</option>
                        <option value="인천">인천광역시</option>
                        <option value="대구">대구광역시</option>
                        <option value="광주">광주광역시</option>
                        <option value="대전">대전광역시</option>
                        <option value="울산">울산광역시</option>
                        <option value="세종">세종시</option>
                        <option value="경기">경기도</option>
                        <option value="강원">강원도</option>
                        <option value="충남">충청남도</option>
                        <option value="충북">충청북도</option>
                        <option value="경북">경상북도</option>
                        <option value="경남">경상남도</option>
                        <option value="전북">전라북도</option>
                        <option value="전남">전라남도</option>
                        <option value="제주">제주도</option>
                    </select>
                    
                    <form action="" method="get">
                        <input type="text" name="q" placeholder="검색어를 입력하세요.">
                        <button type="submit"></button>
                    </form>
                </div>
            </div>
        </div>

        <div class="list-container">
            {% block posts %}
                {% for post in recruit_list %}
                    <div class="recruit-post">
                        <a class="recruit-img" href="{% url 'team_build:detail_recruit' post.id %}">
                            <div 
                            style="background-image: url('../../media/{{post.image}}');" 
                            ></div>
                        </a>
                        <a class="recruit-content" href="{% url 'team_build:detail_recruit' post.id %}">
                            <div>
                                <p class="recruit-title">{{post.title}}</p>
                                <p class="recruit-writer">{{post.writer}}</p>
                            </div>
                            <p class="recruit-hashtag">
                                #{{post.service}}&nbsp&nbsp&nbsp
                                #{% for role in post.get_role_display %}{{role}}{% endfor %}&nbsp&nbsp&nbsp
                                #{{post.get_locate_display}}
                            </p>
                            <p class="recruit-detail">{{post.detail}}</p>
                        </a>
                        
                        <a class="recruit-like" href="{% if user.is_authenticated %} {% url 'team_build:recruit_like' post.id %} {% else %} {% url 'users:login' %} {% endif %}">
                            <div style="background-image: url('../../static/img/like_icon.png');"></div>
                        </a>
                    </div>
                {% endfor %}
            {% endblock %}
            <div class="page-container"> 
                <div class="page-wrapper">
                    {% for page in page_range %}
                        <a class="page-box" href="?page={{page}}">{{page}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>   
    {% endblock %}

hackathon/templates/team_build/update_recruit.html
{% extends 'base.html' %}
    <head>
        {% load static %}
        {% block extrahead %}
        <link rel="stylesheet" href="../../../static/css/base.css">
        <link rel="stylesheet" href="../../../static/css/team_build/create_recruit.css">
        {% endblock %}
    </head>
{% block content %}
    <div class="recruit-back-box">
        <div class="recruit-info-title">모집글 작성</div>
        <form action="{% url 'team_build:update_recruit' id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {% if field.label == '이미지:' %} 
                    <div style="margin-bottom: 10px;">{{field.label}}</div>
                    <div>{{field}}</div>
                    <label class="recruit-image-btn" for="id_image">파일 선택</label>
                    <br>
                    <br>
                {% else %}
                    <div>{{field.label}}</div>
                    <div>{{field}}</div>
                    <br>
                {% endif %}
            {% endfor %}
            <div class="recruit-submit-box">
                <button class="recruit-submit" type="submit">저장</button>
            </div>
        </form>
    </div>
{% endblock %}