hackathon/chat/urls.py
# chat/urls.py
from django.urls import path

from .views import *

app_name = 'chat'

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
    path('<str:me_id>/<str:opp_id>/', create_chat_room, name='create_chat_room'),
]

hackathon/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('main.urls', namespace='main')),

    path('users/', include('users.urls', namespace='users')),

    path('recruit/', include('team_build.urls', namespace='recruit')),
    
    path('portfolio/', include('mypf.urls', namespace='portfolio')),

    path('mypage/', include('mypage.urls', namespace='mypage')),

    path('scout/', include('scout.urls', namespace='scout')),
    
    path('chat/', include('chat.urls', namespace='chat')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hackathon/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', main, name="main"),
]

hackathon/mypf/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'mypf'

urlpatterns = [
    path('<int:id>', profile, name='profile'),
    path('<int:user_id>/create_pf/', create_portfolio, name="create_pf"),
    path('<int:user_id>/<int:pf_id>/', detail_portfolio, name='detail_pf'),
    path('<int:user_id>/update/<int:pf_id>/', update_portfolio, name="update_pf"),
    path('<int:user_id>/delete/<int:pf_id>/', delete_portfolio, name='delete_pf'),
]

hackathon/scout/urls.py
from django.urls import path
from .views import *

app_name='scout'

urlpatterns = [
    # 유저 검색
    path('', user, name='user'),
    path('<str:input_role>', user_search, name='user_search'),
    path('search_text/<str:input_text>', user_search_text, name='user_search_text'),

    # 유저 찜
    path('user_like/<int:user_id>', user_like, name="user_like"),
]

hackathon/users/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

hackathon/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" href="../static/img/favicon.ico" type="image/x-icon">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Moa - 더 모아</title>
    <link rel="stylesheet" href="../../../static/css/base.css">
    {% block extrahead %}
    {% endblock %}
</head>
<body>
    <header>
        <nav class="nav-container">
            <ul class="nav-wrapper">
                <li class="logo">
                    <a href="{% url 'main:main' %}">
                        <div class="logo-img" style="background-image: url('../../../static/img/logo.png');"></div>
                    </a>
                </li>

                <li class="url-container">
                    <a href="{% url 'team_build:team_build' %}">팀 빌딩</a>
                    <a href="{% url 'scout:user' %}">스카우트</a>
                    <a href="{% if user.is_authenticated %} {% url 'mypf:profile' user.id %} {% else %} {% url 'users:login' %} {% endif %}">마이 포트폴리오</a>
                </li>

                <li class="{% if user.is_authenticated %} user-container {% endif %}">
                    <a href="{% if user.is_authenticated %} {% if user.is_authenticated %} {% url 'chat:index' %} {% else %} {% url 'users:login' %} {% endif %} {% else %} {% url 'users:login' %} {% endif %}">    
                        {% if user.is_anonymous %}
                        <div class="chat-img anonymous"></div>
                        {% else %}
                        <div class="chat-img"></div>
                        {% endif %}
                    </a>
                    {% if user.is_authenticated %}
                    <div class="profile-img"></div>
                    <a class="user-name"href="{% url 'mypage:mypage' user.id %}">{{user.name}}</a>
                    <a class="logout" href="{% url 'users:logout' %}">로그아웃</a>
                    {% else %}
                    <a class="btn login" href="{% url 'users:login' %}">로그인</a>
                    <a class="btn signup" href="{% url 'users:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
            
        </nav>
    </header>
    
    {% block content %}
    {% endblock %}
    
    <footer>
        <div>
            <div class="footer-img" style="background-image: url('../../../static/img/footer_logo.png');"></div>
        </div>
        
        <div>
            <p>TEAM. TheMoa <br>
                Likelion_9th @HANYANG Univ ERICA <br>
                경기도 안산시 상록구 한양대학로 55</p>
        </div>
    </footer>
</body>
</html>