hackathon/chat/urls.py
# chat/urls.py
from django.urls import path

from .views import *

app_name = 'chat'

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
    path('<str:me_id>/<str:opp_id>/', create_chat_room, name='create_chat_room'),
]

hackathon/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path('', include('main.urls', namespace='main')),

    path('users/', include('users.urls', namespace='users')),

    path('recruit/', include('team_build.urls', namespace='recruit')),
    
    path('portfolio/', include('mypf.urls', namespace='portfolio')),

    path('mypage/', include('mypage.urls', namespace='mypage')),

    path('scout/', include('scout.urls', namespace='scout')),
    
    path('chat/', include('chat.urls', namespace='chat')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hackathon/mypage/urls.py
from django.urls import path
from .views import *

app_name = 'mypage'

urlpatterns = [
    path('<int:user_id>', mypage, name="mypage"),
]

hackathon/mypf/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'mypf'

urlpatterns = [
    path('<int:id>', profile, name='profile'),
    path('<int:user_id>/create_pf/', create_portfolio, name="create_pf"),
    path('<int:user_id>/<int:pf_id>/', detail_portfolio, name='detail_pf'),
    path('<int:user_id>/update/<int:pf_id>/', update_portfolio, name="update_pf"),
    path('<int:user_id>/delete/<int:pf_id>/', delete_portfolio, name='delete_pf'),
]

hackathon/scout/urls.py
from django.urls import path
from .views import *

app_name='scout'

urlpatterns = [
    # 유저 검색
    path('', user, name='user'),
    path('<str:input_role>', user_search, name='user_search'),
    path('search_text/<str:input_text>', user_search_text, name='user_search_text'),

    # 유저 찜
    path('user_like/<int:user_id>', user_like, name="user_like"),
]

hackathon/users/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

hackathon/mypage/models.py
from django.db import models

hackathon/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField

# from team_build.models import LOCATE_CHOICES

LOCATE_CHOICES = [
    ('','미정'),
    ('서울','서울특별시'),
    ('부산','부산광역시'),
    ('인천','인천광역시'),
    ('대구','대구광역시'),
    ('광주','광주광역시'),
    ('대전','대전광역시'),
    ('울산','울산광역시'),
    ('세종','세종시'),
    ('경기','경기도'),
    ('강원','강원도'),
    ('충남','충청남도'),
    ('충북','충청북도'),
    ('경북','경상북도'),
    ('경남','경상남도'),
    ('전북','전라북도'),
    ('전남','전라남도'),
    ('제주','제주도'),
]
# User
CAREER_CHOICES = [
    ('0','1년 미만'),
    ('1','1년'),
    ('2','2년'),
    ('3','3년'),
    ('4','4년'),
    ('5','5년'),
    ('6','6년'),
    ('7','7년'),
    ('8','8년'),
    ('9','9년'),
    ('10','10년 이상'),
]

STATE_CHOICES = [
    ('','미입력'),
    ('ATTENDING','재학중'),
    ('ABSENCE','휴학중'),
    ('SEARCHING','구직중'),
    ('WORKING','재직중'),
]

ROLE_CHOICES = [
    ('Developer', '개발자'),
    ('Designer', '디자이너'),
    ('Planner', '기획자'),
    ('Etc', '그 외'),
]

# 회원 정보
class User(AbstractUser):
    image = models.ImageField(default="image/users/none/profile_default.png", upload_to="image/users" , blank=True, null=False)
    name = models.CharField(default='', max_length=300)
    birth_date = models.DateField(default=timezone.now)
    address_sido = models.CharField(default='', choices=LOCATE_CHOICES, max_length=200)
    address_gungu = models.CharField(default='', max_length=200)
    career = models.CharField(default='0', max_length=200, choices=CAREER_CHOICES)
    state = models.CharField(default='', blank=True, null=False, max_length=200, choices=STATE_CHOICES)
    role = MultiSelectField(default='Etc', choices=ROLE_CHOICES, max_choices=4, max_length=200)
    intro = models.TextField(default="", blank=True, null=False)

hackathon/mypage/views.py
from scout.models import LikeUser
from django.shortcuts import get_object_or_404, redirect, render
from team_build.models import Recruit, Comment

from users.models import User
from team_build.models import LikeRecruit

def mypage(request, user_id):
    current_user = None
    if request.user.id:
        current_user = User.objects.get(pk=request.user.id)
    
    # 내가 쓴 글, 내가 쓴 댓글 불러오기
    my_recruits = Recruit.objects.filter(writer_username=request.user).order_by('-id')
    my_comments = Comment.objects.filter(user=request.user).order_by('-id')
    
    # 찜한 게시글 불러오기
    objects = LikeRecruit.objects.filter(user=user_id)
    recruits = []
    for obj in objects:
        recruits.append(Recruit.objects.get(pk=obj.recruit_key.id))
    # 중복 항목 제거
    recruits = list(dict.fromkeys(recruits))

    # 찜한 유저 불러오기
    objects = LikeUser.objects.filter(user=user_id)
    users = []
    for obj in objects:
        users.append(User.objects.get(pk=obj.user_key.id))
    users = list(dict.fromkeys(users))

    context = {
        'current_user':current_user,
        'my_recruits':my_recruits,
        'my_comments':my_comments,
        'recruits':recruits,
        'users':users,
    }
    return render(request, 'mypage/mypage.html', context)

hackathon/templates/mypage/create_pf.html
{% extends 'base.html' %}
<head>
    {% load static %}
    {% block extrahead %}
    {% endblock %}
</head>

{% block content %}
    <form action="{% url 'mypage:create_pf' user_id %}" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">작성</button>
    </form>
{% endblock %}

hackathon/templates/mypage/detail_pf.html
{% extends 'base.html' %}
    <head>
        {% load static %}
        {% block extrahead %}
        {% endblock %}
    </head>
{% block content %}
    <p>{{pf.title}}</p>
    <div>{{pf.detail | safe}}</div>
    <a href="{% url 'mypage:update_pf' user_id pf_id %}">수정하기</a>
    <a href="{% url 'mypage:delete_pf' user_id pf_id %}">삭제하기</a>
{% endblock %}

hackathon/templates/mypage/mypage.html
{% extends '../base.html' %}
<head>
    {% load static %}
    {% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="../../static/css/mypage/mypage.css">
    <style>
        .profile-img {
            background-image: url('../../media/{{user.image}}');
        }
    </style>
    {% endblock %}
</head>
{% block content %}
    <div class="mypage-background-img"></div>

    <div class="profile-box">
        <div class="profile-img-big">
            <img src="../../media/{{user.image}}">
        </div>
        <div class="profile-content">
             <div class="profile-content-item" style="font-size: 17px; font-weight: bold;">{{user.name}}</div>
             <div class="profile-content-item">{{user.intro}}</div>
       </div>
    </div>

    <div class="content-menu-box">
        <button class="content-menu-btn" box_id="1" onclick="menuBtn(this)" style="background-color: rgba(228, 236, 245, 1);">내가 쓴 글 / 댓글</button>
        <button class="content-menu-btn" box_id="2" onclick="menuBtn(this)">내가 찜한 글 / 유저</button>
    </div>
    
    <div class="content-back">
        <div class="content-box box1">
            <div class="content-box-container">
                <div class="content-box-title">내가 쓴 글</div>
                {% for recruit in my_recruits %}
                    <div class="content-box-item" onclick="location.href='/recruit/{{recruit.id}}/'">
                        <div class="content-box-item-img" style="background-image: url('../../media/{{recruit.image}}');"></div>
                        <div class="col">
                            <div class="row">
                                <div class="title">{{recruit.title}}</div>
                                <div class="writer">{{recruit.writer}}</div>
                            </div>
                            <div class="role-location"># {{recruit.get_role_display}} # {{recruit.get_locate_display}}</div>
                            <div class="detail">{{recruit.detail}}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="content-box-container">
                <div class="content-box-title">내가 쓴 댓글</div>
                {% for comment in my_comments %} 
                    <div class="content-box-item comment" onclick="location.href='/recruit/{{comment.recruit_id.id}}/'">
                        <div class="row">
                            <div class="comment-content">{{comment.content}}</div>
                            <div class="comment-date">{{comment.date}}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="content-box box2" style="display: none;">
            <div class="content-box-container">
                <div class="content-box-title">관심 글</div>
                {% for recruit in recruits %}
                    <div class="content-box-item" onclick="location.href='/recruit/{{recruit.id}}/'">
                        <div class="content-box-item-img" style="background-image: url('../../media/{{recruit.image}}');"></div>
                        <div class="col">
                            <div class="row">
                                <div class="title">{{recruit.title}}</div>
                                <div class="writer">{{recruit.writer}}</div>
                            </div>
                            <div class="role-location"># {{recruit.get_role_display}} # {{recruit.get_locate_display}}</div>
                            <div class="detail">{{recruit.detail}}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="content-box-container">
                <div class="content-box-title">관심 유저</div>
                <div class="users-container">
                    {% for user_instance in users %}
                    <div class="user-card" onclick="location.href='/portfolio/{{user_instance.id}}'">
                        <div class="card-nav">
                            <a href="">
                                <div class="chat" style="background-image: url('../../static/img/scout/chat.png');"></div>
                            </a>
                            <a href="{% if user.is_authenticated %} {% url 'scout:user_like' user_instance.id %} {% else %} {% url 'users:login' %} {% endif %}">
                                <div class="wish" style="background-image: url('../../static/img/like_active.png');"></div>
                            </a>
                        </div>
                        
                        <hr>

                        {% if user_instance.image %}
                        <img class="user-img" src="../../media/{{user_instance.image}}" alt="프로필 사진">
                        {% else %}
                        <img class="user-img" src="../../static/img/profile_default.png" alt="프로필 사진">
                        {% endif %}

                        <div class="user-name">
                            {{user_instance.name}}
                        </div>
                
                        <div class="user-address">
                            {{user_instance.get_address_sido_display}}
                        </div>
                        
                        <div class="card-content"> 
                            <p class="user-info">
                                <br>
                                #{{user_instance.get_role_display}}
                                <br>
                                #{{user_instance.get_state_display}}
                                <br>
                            </p>
                        
                            <div class="user-intro">
                                {{user_instance.intro}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="../../../static/js/mypage/mypage.js"></script>
{% endblock %}

hackathon/templates/mypage/profile.html
{% extends 'base.html' %}
    <head>
        {% load static %}
        {% block extrahead %}
        {% endblock %}
    </head>
{% block content %}
    <p>이름 : {{obj.name}}</p>
    <p>생년월일 : {{obj.birth_date}}</p>
    <p>거주지역 : {{obj.address_sido}} {{obj.address_gungu}}</p>
    <p>경력 : {{obj.get_career_display}}</p>
    <p>상태 : {{obj.get_state_display}}</p>
    <p>역할 : {{obj.get_role_display}}</p>
    <p>포트폴리오
        {% for pf in pfs %}
            <p>{{pf.title}}</p>
            <a href="{% url 'mypage:detail_pf' user_id pf.id %}">자세히</a>
        {% endfor %}
    </p>
{% endblock %}

hackathon/templates/mypage/update_pf.html
{% extends 'base.html' %}
<head>
    {% load static %}
    {% block extrahead %}
    {% endblock %}
</head>

{% block content %}
    <form action="{% url 'mypage:update_pf' user_id pf_id %}" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">수정</button>
    </form>
{% endblock %}